### ISSUE TITLE
SVG not visible in courses.html

### ISSUE THREAD

**Issue by moonLight-7k** [moonLight-7k/suhelkhan.github.io#3]
In course page the .svg image is not working  beside achievements
 - File [Courses.html](https://github.com/moonLight-7k/suhelkhan.github.io/blob/main/contact.html)

**Comment by Emmarie-Ahtunan** [comment]
Have a look at your about.html page. I think that's where you want to place the .svg image next to achievements (but maybe not).

https://moonlight-7k.github.io/suhelkhan.github.io/about.html

**Comment by moonLight-7k** [comment]
It was issue of the scr link at line 63.
